# Change baseurl before deploy
baseurl = "https://cyberlyon.blog/"
languageCode = "en-us"
title = "CyberLyon"

# Theme i18n support
defaultContentLanguage = "en"

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
hasCJKLanguage = false


[pagination]
pagerSize = 5


[params]
mainSections = ["notes", "post"]


[services]
  [services.disqus]
    shortname = "cyberlyon-blog"
